---
- name: debian | Installing Pre-Reqs
  apt:
    name: [ 'apt-transport-https', 'jq' ]
    state: present
    force: true
  become: true

- name: debian | Adding K8s Repo Key
  apt_key:
    url: "{{ k8s_debian_repo_info['key'] }}"
    state: present
  become: true

- name: debian | Adding K8s Repo
  apt_repository:
    repo: "{{ k8s_debian_repo_info['repo'] }}"
    state: present
  become: true

- name: debian | Pinning K8s Version
  template:
    src: etc/apt/preferences.d/k8s.pref.j2
    dest: /etc/apt/preferences.d/k8s.pref
  become: true
  notify: [ "update apt cache" ]

- name: debian | Installing K8s Packages
  apt:
    name: "{{ k8s_debian_packages }}"
    state: present
    force: true
  become: true
