---
# tasks file for ansible-k8s

- include_tasks: set_facts.yml

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: services.yml

- include_tasks: swap.yml

- include_tasks: init_cluster.yml

- include_tasks: network.yml

- include_tasks: join_cluster.yml
  when: inventory_hostname != k8s_master

- include_tasks: cluster_summary.yml

- include_tasks: users.yml

- include_tasks: pods.yml
  when: >
        (inventory_hostname == k8s_master) and
        k8s_cluster_init

- include_tasks: cluster_services.yml
  when: >
        (inventory_hostname == k8s_master) and
        k8s_cluster_init

- include_tasks: helm.yml
  when: >
    k8s_helm_install|bool
    and (inventory_hostname == k8s_master)

- include_tasks: reset_cluster.yml
  when: k8s_reset_cluster
