---
# tasks file for ansible-k8s

- name: Gather required facts
  include_tasks: set_facts.yml

- name: Install K8s resources for Debain
  include_tasks: debian.yml
  when: >
    ansible_os_family == "Debian"

- name: Enable K8s services {{ k8s_services }}
  include_tasks: services.yml

- name: Disable Swap
  include_tasks: swap.yml

- name: Initialize Master Node with Token
  include_tasks: init_cluster.yml

- name: Setting up overlay network
  include_tasks: network.yml

- name: Join additional nodes
  include_tasks: join_cluster.yml
  when: >
    inventory_hostname != k8s_master

- name: Display at node states
  include_tasks: cluster_summary.yml

- name: Setting up user-based kubeconfig
  include_tasks: users.yml

- name: Display at pod states
  include_tasks: pods.yml
  when: >
        k8s_cluster_init
        and (inventory_hostname == k8s_master)

- name: Display at service states
  include_tasks: cluster_services.yml
  when: >
        k8s_cluster_init
        and (inventory_hostname == k8s_master)

- name: Install and deploy helm resources
  include_tasks: helm.yml
  when: >
    k8s_helm_install|bool
    and (inventory_hostname == k8s_master)

- name: Reset the Kubernetes cluster
  include_tasks: reset_cluster.yml
  when: >
    k8s_reset_cluster
