---
- name: reset_cluster | Resetting Cluster
  command: kubeadm reset {{ -f if k8s_version is version_compare(1.13.0, '>=') }}
  become: true
  tags:
    - k8s_reset
  when: >
        k8s_reset_cluster and
        inventory_hostname in groups[k8s_cluster_group]
