---
- name: swap | Removing swapfile From /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
  become: true

- name: swap | Disabling Swap
  command: swapoff -a
  register: _swap
  changed_when: >
    _swap['stdout']
  failed_when: >
    _swap['stderr']
  become: true
